// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type User struct {
	UserID         int32
	Email          string
	Username       string
	HashedPassword string
	FirstName      string
	LastName       string
	DateOfBirth    time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
